name: Trigger Training Pipeline

on:
  workflow_dispatch:
  
jobs:
  cd:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2.4.2

    - uses: tj-actions/branch-names@v6.4
      name: Get branch name
      id: branch-name
      
    - name: Running on the default branch.
#       if: steps.branch-name.outputs.is_default == 'true'
      run: |
        echo "Running on default: ${{ steps.branch-name.outputs.current_branch }}"      
      
